### ISSUE TITLE
inoperative plugin

### ISSUE THREAD

**Issue by dhawker** [gigibu5/OctoLight#6] opened 2021-01-21 17:07 UTC
Just installed your new plugin with the plugin manager, no problem.
re-booted Octoprint
lightbulb button appears as expected
cursor changes from selection hand icon to indicator icon and cannot select or press button.

suggestion, it would also be useful if the light could be switched on when Octolapse triggers to take picture and off after picture taken.  No need to leave light on continuously when printing overnight.

**Comment by gigibu5** [comment] 2021-01-21 18:42
Hmmm, I don't see how that would be usefull. You want to use the light as a flash?

**Comment by dhawkerg1** [comment] 2021-01-21 19:49
something similar, but the non-operation is a bit more pressing

**Comment by gigibu5** [comment] 2021-01-21 20:00
If I understand correctly, you want to use this with the Octoprints timelapse feature, so you can film timelapses at night?

**Comment by Member1773** [comment] 2021-01-21 22:04
I think he means, that there is no visual feedback when the button (which is an anchor-element) is pressed.

**Comment by gigibu5** [comment] 2021-01-21 22:08
Ah OK, then this is a duplicate of issue #1

**Closed** 2021-01-22 01:10 UTC
Labels: duplicate

**Comment by dhawker** [comment] 2021-01-22 10:42
Not the Octoprint timelapse, the Octolapse time lapse which moves the printhead out of shot for the picture. This would be more practical

**Comment by gigibu5** [comment] 2021-01-22 10:44
I probably wont add it, maybe at a later date (v0.2.0 maybe)
