### ISSUE TITLE
Having two indipentend buttons for two light sources

### ISSUE THREAD

**Issue by kjoussen** [gigibu5/OctoLight#18] opened 2021-01-30 22:22 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by kjoussen** [comment] 2021-01-30 22:23
I have two LED-Stripes and want to have them switched indipendently.
So two GPIOs and two relays but also two buttons.
Possible?

**Comment by gigibu5** [comment] 2021-01-30 22:25
Duplicate of #11

**Closed by gigibu5** 2021-01-30 22:25 UTC
Labels: duplicate
